version: '3'
services:
  backend:
    image: backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - SECRET_KEY=${SECRET_KEY}
      - CLOUD_CREDS=${CLOUD_CREDS}
    build:
      context: backend
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
  ml:
    image: ai
    environment:
      - CLOUD_CREDS=${CLOUD_CREDS}
    build:
      context: ai
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - .:/app
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
