"""empty message

Revision ID: c11cdabe782c
Revises: f6eac3a9aded
Create Date: 2024-05-12 07:50:18.083717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11cdabe782c'
down_revision = 'f6eac3a9aded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('possible_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_person_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('in_search_person_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'in_search_person', ['in_search_person_id'], ['id'])
        batch_op.create_foreign_key(None, 'found_persons', ['found_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('possible_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('match_score')
        batch_op.drop_column('in_search_person_id')
        batch_op.drop_column('found_person_id')

    # ### end Alembic commands ###
