name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: create credentials file
      run: |
        echo ${{ secrets.CLOUD_CREDS }} > backend/cloud_credentials.json
        echo ${{ secrets.CLOUD_CREDS }} > ai/cloud_credentials.json
    - name: Docker Compose
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PSWD: ${{ secrets.DB_PSWD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLOUD_CREDS: ${{ secrets.CLOUD_CREDS }}
      run: docker compose up -d --force-recreate --build
